# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

  job2:    
    runs-on: windows-latest
    needs: [job1]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'Write-Output "test1";'

  job3:    
    runs-on: macos-latest
    needs: [job2]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

  job4:    
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
